#!/usr/local_rwth/bin/zsh




#SBATCH --job-name=syk_nn81 # The job name.
#SBATCH -c 48        # The number of cpu cores to use.
#SBATCH --time=47:59:00              # The time the job will take to run.
#SBATCH --mem-per-cpu=3200M        # The memory the job will use per cpu core.
### SBATCH --account=rwth0722
#SBATCH --mail-type=NONE
#SBATCH --mail-user=passetti@physik.rwth-aachen.de


#SBATCH --output=/home/yz004406/neural_network_cl/syk_AI/NN_cluster/Random_hopping/Bash/rh408
#

### Change to the work directory
cd /home/yz004406/neural_network_cl/syk_AI/NN_cluster/Random_hopping
### Execute your application



module load python/3.8.11



mpirun -np 24 python3 main_rh.py 40 8 1 500 1000

echo $?

date

